parameters:
  pool:
  azureSubscription:
  location: 'West Europe'
  environmentName:
  appName:

jobs:
- deployment: DeployAzureFunctionApp
  pool:
    name: ${{ parameters.pool }}
    demands:
    - ReleaseEnvironment -equals ${{ parameters.environmentName }}
    workspace:
      clean: all

  environment: ${{ parameters.environmentName }}

  strategy:
    runOnce:
      deploy:
        steps:

        - task: AzureAppServiceSettings@1
          displayName: 'Apply Function App Settings'
          inputs:
            azureSubscription: ${{ parameters.azureSubscription }}
            appName: ${{ parameters.appName }}
            resourceGroupName: ''
            appSettings: |
              [
                { "name": "PaymentsConnectionString", "value": "$(DasPaymentsConnectionStringRW)" },
                { "name": "ServiceBusConnectionString", "value": "$(ServiceBusSAPServFabPrimaryConnectionStringDAS)" },
                { "name": "SLDJobManagementAPIEndpoint", "value": "$(SLDJobManagementAPIEndpoint)" }
               
              ]

        - task: AzureFunctionApp@2
          displayName: 'Azure Function App Deploy'
          inputs:
            azureSubscription: ${{ parameters.azureSubscription }}
            appType: functionAppLinux
            isFlexConsumption: true
            appName: ${{ parameters.appName }}
            package: '$(pipeline.workspace)/CollectionPeriod-FunctionApp/CollectionPeriod-FunctionApp.zip'
