parameters:
  pool:
  azureSubscription:
  location: 'West Europe'
  environmentName:
  appName:
  ServiceBusNamespace:

jobs:
- deployment: DeployAzureFunctionApp
  pool:
    name: ${{ parameters.pool }}
    demands:
    - ReleaseEnvironment -equals ${{ parameters.environmentName }}
    workspace:
      clean: all

  environment: ${{ parameters.environmentName }}

  strategy:
    runOnce:
      deploy:
        steps:

        - task: AzureAppServiceSettings@1
          displayName: 'Apply Function App Settings'
          inputs:
            azureSubscription: ${{ parameters.azureSubscription }}
            appName: ${{ parameters.appName }}
            resourceGroupName: ''
            appSettings: |
               [
                { "name": "PaymentsConnectionString", "value": "$(DasPaymentsConnectionStringRW)" },
                { "name": "ServiceBusConnectionString", "value": "$(ServiceBusSAPServFabPrimaryConnectionStringDAS)" },
                { "name": "SLDJobManagementAPIEndpoint", "value": "$(SLDJobManagementAPIEndpoint)" },
                { "name": "AzureAd__ClientId", "value": "$(CollectionPeriod-SLDAPI-ClientId)" },
                { "name": "AzureAd__TenantId", "value": "$(CollectionPeriod-SLDAPI-TenantId)" },
                { "name": "AzureAd__Audience", "value": "$(CollectionPeriod-SLDAPI-Audience)" },
                { "name": "AzureAd__ClientSecret", "value": "$(CollectionPeriod-SLDAPI-ClientSecret)" },
                { "name": "Thumbprint", "value": "$(CollectionPeriod-Thumbprint)" },
                { "name": "AzureAd__Instance", "value": "https://login.microsoftonline.com/" },
                { "name": "CollectionPeriodQueueName", "value": "sfa-das-payments-collectionperiod" },
                { "name": "CollectionPeriodSubscriptionName", "value": "sfa-das-payments-collectionperiod" },
                { "name": "PaymentsTopicName", "value": "bundle-1" },
                { "name": "ServiceBusNamespace", "value": ${{ parameters.ServiceBusNamespace }} }
                
               
               ]

        - task: AzureFunctionApp@2
          displayName: 'Azure Function App Deploy'
          inputs:
            azureSubscription: ${{ parameters.azureSubscription }}
            appType: functionAppLinux
            isFlexConsumption: true
            appName: ${{ parameters.appName }}
            package: '$(pipeline.workspace)/CollectionPeriod-FunctionApp/CollectionPeriod-FunctionApp.zip'
